from __future__ import annotations

import os
import sys
from logging.config import fileConfig

from alembic import context
from pgvector.sqlalchemy import Vector
from sqlalchemy import engine_from_config, pool

# Add project root to sys.path so ring_detector is importable when running
# alembic from the CLI (e.g. `alembic upgrade head`).
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from ring_detector.config import settings  # noqa: E402
from ring_detector.database import Base  # noqa: E402

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Override sqlalchemy.url from settings so the DB password never lives in alembic.ini
config.set_main_option("sqlalchemy.url", settings.db.url)

target_metadata = Base.metadata


# --- pgvector autogenerate support ---

def render_item(type_: str, obj: object, autogen_context: object) -> str | bool:
    """Render pgvector Vector columns correctly in autogenerated migrations."""
    if type_ == "type" and isinstance(obj, Vector):
        autogen_context.imports.add("from pgvector.sqlalchemy import Vector")
        return f"Vector({obj.dim})"
    return False


def compare_type(
    context: object,
    inspected_column: object,
    metadata_column: object,
    inspected_type: object,
    metadata_type: object,
) -> bool | None:
    """Tell Alembic how to detect changes in Vector column dimensions."""
    if isinstance(metadata_type, Vector) and isinstance(inspected_type, Vector):
        return inspected_type.dim != metadata_type.dim
    return None


# --- Migration runners ---

def run_migrations_offline() -> None:
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        render_item=render_item,
        compare_type=compare_type,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = engine_from_config(
        config.get_section(config.config_ini_section),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            render_item=render_item,
            compare_type=compare_type,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
